runtime: python39

handlers:
# Serve static files
- url: /styles.css
  static_files: styles.css
  upload: styles.css

- url: /script.js
  static_files: script.js
  upload: script.js

- url: /(.+\.(html|css|js|png|jpg|jpeg|gif|ico|svg))
  static_files: \1
  upload: (.+\.(html|css|js|png|jpg|jpeg|gif|ico|svg))

# Serve the main page
- url: /
  static_files: index.html
  upload: index.html

# Serve other HTML pages
- url: /(.+)
  static_files: \1.html
  upload: (.+)\.html

# Security headers
env_variables:
  SECURE_SSL_REDIRECT: "true" 